# Generated by Django 5.1.15 on 2026-06-09 22:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_retirada', models.DateTimeField(verbose_name='data/hora de retirada')),
                ('data_prevista_devolucao', models.DateTimeField(verbose_name='data/hora prevista de devolução')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor da diária')),
                ('km_saida', models.PositiveIntegerField(verbose_name='quilometragem de saída')),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], max_length=20, verbose_name='forma de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado')], db_index=True, default='ativo', max_length=20, verbose_name='status')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='devolução real')),
                ('km_retorno', models.PositiveIntegerField(blank=True, null=True, verbose_name='quilometragem de retorno')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor final cobrado')),
                ('multa_atraso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='multa por atraso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='clientes.cliente', verbose_name='cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='veiculos.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'locação',
                'verbose_name_plural': 'locações',
                'ordering': ['-data_retirada'],
                'indexes': [models.Index(fields=['status', 'data_retirada'], name='locacoes_lo_status_f96a92_idx')],
            },
        ),
    ]
