# Generated by Django 5.1.15 on 2026-06-09 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(max_length=80, verbose_name='modelo')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950)], verbose_name='ano')),
                ('placa', models.CharField(db_index=True, max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Use o formato ABC1234 ou ABC1D23.', regex='^[A-Z]{3}[0-9][0-9A-Z][0-9]{2}$')], verbose_name='placa')),
                ('quilometragem_atual', models.PositiveIntegerField(default=0, verbose_name='quilometragem atual')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em manutenção')], db_index=True, default='disponivel', max_length=20, verbose_name='status')),
                ('categoria', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('suv', 'SUV'), ('van', 'Van')], db_index=True, max_length=20, verbose_name='categoria')),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor de compra')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor da parcela')),
                ('qtd_parcelas', models.PositiveIntegerField(blank=True, null=True, verbose_name='qtd. de parcelas')),
                ('vencimento_ipva', models.DateField(blank=True, null=True, verbose_name='vencimento do IPVA')),
                ('vencimento_seguro', models.DateField(blank=True, null=True, verbose_name='vencimento do seguro')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('manutencao_motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo da manutenção')),
                ('manutencao_retorno_previsto', models.DateField(blank=True, null=True, verbose_name='retorno previsto da manutenção')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ['marca', 'modelo'],
                'indexes': [models.Index(fields=['status', 'categoria'], name='veiculos_ve_status_19206f_idx')],
            },
        ),
    ]
