# Generated by Django 5.1.15 on 2026-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='vencimento_seguro',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='parcelas_pagas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='parcelas já pagas'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tem_rastreador',
            field=models.BooleanField(default=False, verbose_name='possui rastreador do sistema'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_rastreador',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor mensal do rastreador'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em manutenção'), ('vendido', 'Vendido')], db_index=True, default='disponivel', max_length=20, verbose_name='status'),
        ),
    ]
