# Generated by Django 5.1.15 on 2026-06-09 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacoes', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_infracao', models.DateField(verbose_name='data da infração')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('contestado', 'Contestado')], db_index=True, default='pendente', max_length=20, verbose_name='status')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='locacoes.locacao', verbose_name='contrato associado')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='veiculos.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'multa',
                'verbose_name_plural': 'multas',
                'ordering': ['-data_infracao'],
            },
        ),
    ]
