# Generated by Django 5.1.15 on 2026-06-09 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo_servico', models.CharField(choices=[('oleo', 'Troca de óleo'), ('revisao', 'Revisão'), ('pneus', 'Pneus'), ('freios', 'Freios'), ('outro', 'Outro')], db_index=True, max_length=20, verbose_name='tipo de serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data', models.DateField(verbose_name='data')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo')),
                ('km_momento', models.PositiveIntegerField(verbose_name='quilometragem no momento')),
                ('proxima_revisao_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='próxima revisão (km)')),
                ('proxima_revisao_data', models.DateField(blank=True, null=True, verbose_name='próxima revisão (data)')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='veiculos.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'manutenção',
                'verbose_name_plural': 'manutenções',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['veiculo', '-data'], name='manutencao__veiculo_8e52ee_idx')],
            },
        ),
    ]
