# Generated by Django 5.1.15 on 2026-06-09 22:16

import apps.clientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(db_index=True, max_length=11, unique=True, validators=[apps.clientes.validators.validate_cpf], verbose_name='CPF')),
                ('cnh', models.CharField(max_length=20, verbose_name='número da CNH')),
                ('validade_cnh', models.DateField(verbose_name='validade da CNH')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('logradouro', models.CharField(max_length=150, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=80, verbose_name='complemento')),
                ('bairro', models.CharField(max_length=80, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
    ]
